set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_SYSTEM_PROCESSOR x86_64)

set(CMAKE_C_COMPILER C:/clang/bin/clang.exe)
set(CMAKE_CXX_COMPILER C:/clang/bin/clang++.exe)

set(CMAKE_C_COMPILER_TARGET x86_64-w64-mingw32)
set(CMAKE_CXX_COMPILER_TARGET x86_64-w64-mingw32)


set(CMAKE_C_LINK_EXECUTABLE
        "<CMAKE_C_COMPILER> <OBJECTS> -o <TARGET> <LINK_FLAGS>"
)
set(CMAKE_CXX_LINK_EXECUTABLE
        "<CMAKE_CXX_COMPILER> <OBJECTS> -o <TARGET> <LINK_FLAGS>"
)
